---
# List the Dockerfile for image
image:
  file: Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Check Setup
    command: |
      clear
      echo "=============="
      echo "    Welcome   "
      echo "=============="
      echo ""
      pyenv versions

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  # x11vnc
  - port: 5900
    onOpen: ignore
# noVNC
  - port: 6080
    onOpen: open-browser
# jupyter
  - port: 8888
    onOpen: ignore

# Install VSCode Extensions
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python